### ISSUE TITLE
Problem at Install

### ISSUE THREAD

**Issue by Rootkage** [simon-fraser/MusicTube-Player#11]
Hello :) 

I have a problem when I want to Install the program but I have htis problems. Is that program realy for Windows too? Or what I made wrong?
![Unbenannt](https://user-images.githubusercontent.com/41064191/72290184-eecc4400-364c-11ea-9638-b9e2c2693f99.JPG)

**Comment by lagagain** [comment]
I package for some platform(include Windows) on [here](https://github.com/lagagain/MusicTube-Player/releases).   You can download and unzip it.

---------

BTW, when I use `npm run win` command to pack it for Windows, there are some error too. (not the same errors)
(the end, I write a magic number to `electron-packager . "MusicTubePlayer" --platform=win32 --arch=x64 --out=build/win --overwrite --prune=true --icon="assets/musictube.ico" --version-string.ProductName='MusicTube Player' --app-version=`npm --version`  --asar && electron-installer-windows --src build/win/MusicTubePlayer-win32-x64/ --dest build/win/
`)
