### ISSUE TITLE
Releases for all systems

### ISSUE THREAD

**Issue by simon-fraser** [simon-fraser/MusicTube-Player#3]
If anyone has any experience with multi-platform builds for the releases and can lend a hand please let me know, I'm struggling to get packages/releases compiled for anything other than the host system (osx).

**Comment by simon-fraser** [comment]
I have added [electron-installer-windows](https://www.npmjs.com/package/electron-installer-windows) in an effort to create an installer file instead of having to move the exe manually. 
Can anybody can test and let me know if it works alright?

**Comment by deathart** [comment]
https://github.com/simon-fraser/MusicTube-Player/pull/8
